### ISSUE TITLE
Happy-Birthday app is badly configurated

### ISSUE THREAD

**Issue by veitsi** [udacity/Happy-Birthday#1]
this project can not be launched. When i starting it in android studio it gives an error "Error:Cause: peer not authenticated"

**Comment by deepy-it-is** [comment]
check out with the new version of android studio

**Comment by M-ZubairAhmed** [comment]
it works in most system, i think this issue can be closed

**Comment by SudKul** [comment]
Closing this discussion. 
Udacity has recently updated the App in this [commit](https://github.com/udacity/Happy-Birthday/commit/6baf2d487e8f2a15cc1aecb4f975fda8d4745c02).  The Readme file recommends the suitable Android Studio version to make the App run smoothly.
